# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across difserent versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actionss

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: sudo npm ci && sudo npm run preinstall
      - run: sudo npm run build --if-present
      - name: Create env file
        run: |
          sudo touch build/.env
          sudo echo TOKEN="${{ secrets.TOKEN }}" >> build/.env
      - run: |
          sudo touch .env
          sudo echo TOKEN="${{ secrets.TOKEN }}" >> .env
      - name: Running
        run: sudo npm run register
      - run: sudo pm2 restart saveeasily
